spring.application.name=hospitalManagement
server.port= ${PORT:8885}

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=postgres

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

#security config
#spring.security.user.name=abhinav
#spring.security.user.password=abhinav
jwt.secret=YWJoaW5hdnNpbmdosjghdyuiwhb2773y8dh363gr3hrb872873hidn2dnwj83y743dijdoij918u983edun3uidh928dj2j92dh87dy837hd2

#spring.security.oauth2.client.registration.google.client-id= anjndjjd
#spring.security.oauth2.client.registration.google.client-secret=